version: "3.7"
services:
    db:
        container_name: db_postgres
        restart: always
        image: postgres
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            # POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./db/init/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
            - ./pgdata:/var/lib/postgresql/data
    app:
        container_name: decTohex
        restart: always
        volumes:
            - ".:/usr/src/DecToHex_service"
        build: .
        ports:
            - "3000:3000"
        links:
            - db
        depends_on:
            - db